# Session messages configuration for Claude hooks
# Messages related to session management and tracking

# Session lifecycle
session_start:
  message: "🚀 Session started: {session_id}"
  hint: "New work session initialized with tracking capabilities"

session_resume:
  message: "🔄 Session resumed: {session_id}"
  hint: "Continuing previous work session - {duration} since last activity"

session_expire:
  message: "⏰ Session expired: {session_id}"
  hint: "Session was active for {duration} - creating new session"

session_end:
  message: "✅ Session ended: {session_id}"
  hint: "Session completed successfully after {duration}"

# File tracking within sessions
file_added_to_session:
  message: "📝 File added to session: {file_path}"
  hint: "This file can now be modified without documentation blocks"

folder_added_to_session:
  message: "📁 Folder added to session: {folder_path}"
  hint: "Files in this folder can be modified without documentation blocks"

# Session state management
session_data_loaded:
  message: "💾 Session data loaded"
  hint: "Previous session state restored - {files_count} files tracked"

session_data_saved:
  message: "💾 Session data saved"
  hint: "Current session state persisted for future use"

session_cleanup:
  message: "🧹 Session cleanup completed"
  hint: "Expired sessions and temporary data removed"

# Documentation enforcement within sessions
first_access_blocked:
  message: "🚫 First access to documented file blocked"
  hint: "Update documentation at {doc_path} before modifying {file_path}"

subsequent_access_allowed:
  message: "✅ Subsequent access allowed in session"
  hint: "File {file_path} can now be modified - already working on it this session"

documentation_session_warning:
  message: "⚠️ Documentation enforcement active"
  hint: "Files with existing documentation require updates on first access"

# Session statistics and monitoring
session_stats:
  message: "📊 Session statistics"
  hint: "Files modified: {files_modified}, Duration: {session_duration}"

session_activity:
  message: "🔍 Session activity: {activity_type}"
  hint: "Operation: {operation} on {target}"

# Session errors and recovery
session_load_error:
  message: "❌ Session load error"
  hint: "Could not load previous session - starting fresh session"

session_save_error:
  message: "❌ Session save error"
  hint: "Could not save session state - data may be lost"

session_corruption:
  message: "⚠️ Session data corruption detected"
  hint: "Starting new session due to corrupted data"

# Multi-session coordination
session_conflict:
  message: "⚠️ Session conflict detected"
  hint: "Multiple sessions accessing same resources - consider coordination"

session_handoff:
  message: "🔄 Session handoff initiated"
  hint: "Transferring session {old_session} to {new_session}"

# Session configuration
session_config_loaded:
  message: "⚙️ Session configuration loaded"
  hint: "Session timeout: {timeout}s, File tracking: {tracking_enabled}"

session_limits:
  message: "📏 Session limits active"
  hint: "Max files: {max_files}, Max duration: {max_duration}"

# Agent session coordination
agent_session_start:
  message: "🤖 Agent session started: {agent_type}"
  hint: "Agent {agent_type} session linked to main session {session_id}"

agent_session_switch:
  message: "🔄 Agent session switch"
  hint: "From {old_agent} to {new_agent} - maintaining session continuity"

# Work tracking messages
work_period_start:
  message: "⏱️ Work period started"
  hint: "Beginning focused work period - documentation blocks minimized"

work_period_end:
  message: "⏹️ Work period ended"
  hint: "Work period completed - {operations_count} operations performed"

# Session quality metrics
session_efficiency:
  message: "📈 Session efficiency: {efficiency_score}%"
  hint: "Operations per minute: {ops_per_minute}, Blocked operations: {blocked_count}"

session_productivity:
  message: "🎯 Session productivity metrics"
  hint: "Tasks completed: {tasks_completed}, Files modified: {files_modified}"