# System configuration for Claude hooks
# Central configuration for system-wide settings

# Cache configuration
cache:
  ttl: 300  # Cache TTL in seconds (5 minutes)
  max_entries: 1000  # Maximum number of cached entries
  cleanup_interval: 3600  # Cleanup interval in seconds (1 hour)

# Session management
session:
  timeout: 7200  # Session timeout in seconds (2 hours)
  max_files: 100  # Maximum files tracked per session
  auto_cleanup: true  # Automatically cleanup expired sessions
  save_interval: 30  # Save session state every N seconds

# Documentation enforcement
documentation:
  enforcement_enabled: true  # Enable documentation enforcement
  session_based_tracking: true  # Use session-based tracking
  block_first_access: true  # Block first access to documented files
  required_for_important_files: true  # Require docs for files in _absolute_docs

# File system protection
file_protection:
  enabled: true  # Enable file system protection rules
  root_file_restrictions: true  # Restrict root file creation
  env_file_protection: true  # Protect .env files
  dangerous_command_blocking: true  # Block dangerous commands

# Allowed root files (loaded from separate file for flexibility)
allowed_root_files_config: "__claude_hook__allowed_root_files"
valid_test_paths_config: "__claude_hook__valid_test_paths"

# Tool enforcement
tool_enforcement:
  enabled: true  # Enable dynamic tool enforcement
  role_based_restrictions: true  # Restrict tools based on agent role
  block_violations: true  # Block tool usage violations

# Logging configuration
logging:
  enabled: true  # Enable operation logging
  log_level: "INFO"  # Log level: DEBUG, INFO, WARNING, ERROR
  max_log_size: 10485760  # 10MB max log file size
  log_retention_days: 30  # Keep logs for 30 days

# Performance settings
performance:
  lazy_loading: true  # Enable lazy loading of configurations
  async_operations: true  # Use async operations where possible
  batch_processing: true  # Enable batch processing for multiple operations

# Network and timeouts
network:
  connection_timeout: 30  # Network connection timeout in seconds
  read_timeout: 60  # Network read timeout in seconds
  retry_attempts: 3  # Number of retry attempts for failed operations
  retry_delay: 1  # Delay between retries in seconds

# Context injection settings
context_injection:
  enabled: true  # Enable context injection for MCP tools
  cache_context: true  # Cache injected context
  timeout: 10  # Context injection timeout in seconds
  max_context_size: 100000  # Maximum context size in bytes

# Hint system configuration
hints:
  enabled: true  # Enable hint system
  display_pre_hints: true  # Show hints before tool execution
  display_post_hints: true  # Show hints after tool execution
  hint_persistence: true  # Persist hints across sessions

# Agent coordination
agents:
  tracking_enabled: true  # Enable agent state tracking
  role_enforcement: true  # Enforce agent role restrictions
  context_sharing: true  # Enable context sharing between agents
  delegation_tracking: true  # Track agent delegations

# Error handling
error_handling:
  graceful_degradation: true  # Enable graceful degradation on errors
  fallback_mechanisms: true  # Use fallback mechanisms
  error_reporting: true  # Enable error reporting
  recovery_attempts: 3  # Number of recovery attempts

# Security settings
security:
  audit_logging: true  # Enable audit logging
  sensitive_data_protection: true  # Protect sensitive data
  access_control: true  # Enable access control
  secure_defaults: true  # Use secure defaults

# Development settings
development:
  debug_mode: false  # Enable debug mode (more verbose logging)
  dev_shortcuts: false  # Enable development shortcuts
  mock_external_services: false  # Mock external services in dev

# Cleanup and maintenance
maintenance:
  auto_cleanup: true  # Enable automatic cleanup
  cleanup_schedule: "daily"  # Cleanup schedule: hourly, daily, weekly
  temp_file_retention: 86400  # Keep temp files for 24 hours
  log_compression: true  # Compress old log files

# Feature flags
features:
  advanced_caching: true  # Enable advanced caching features
  parallel_processing: true  # Enable parallel processing
  smart_retries: true  # Enable smart retry logic
  adaptive_timeouts: true  # Use adaptive timeout values

# Message formatting
messages:
  include_timestamps: true  # Include timestamps in messages
  include_context: true  # Include context information
  color_coding: false  # Use color coding (not supported in all terminals)
  emoji_support: true  # Use emoji in messages

# Compatibility settings
compatibility:
  legacy_support: false  # Support legacy configuration formats
  migration_warnings: true  # Show migration warnings
  deprecation_notices: true  # Show deprecation notices